import imgProduct1 from './img/product-1.png';
import imgProduct2 from './img/product-2.png';
import imgProduct3 from './img/product-3.png';
import imgProduct4 from './img/product-4.png';
import imgProduct5 from './img/product-5.png';
import imgProduct6 from './img/product-6.png';
import imgProduct7 from './img/product-7.png';
import imgProduct8 from './img/product-8.png';
import imgProduct9 from './img/product-9.png';
import imgProduct10 from './img/product-10.png';
import imgProduct11 from './img/product-11.png';
import imgProduct12 from './img/product-12.png';
import imgProduct13 from './img/product-13.png';
import imgProduct14 from './img/product-14.png';
import imgProduct15 from './img/product-15.png';
import imgProduct16 from './img/product-16.png';
import imgProduct17 from './img/product-17.png';
import imgProduct18 from './img/product-18.png';
import imgProduct19 from './img/product-19.png';
import imgProduct20 from './img/product-20.png';
import imgProduct21 from './img/product-21.png';
import imgProduct22 from './img/product-22.png';
import imgProduct23 from './img/product-23.png';
import imgProduct24 from './img/product-24.png';

const ArrProducts = [
    {
        id: 1,
        imgProduct: imgProduct1,
        productSales:'-30%',
        productPriceCart:'44',
        productNoCart:'48',
        productName: 'Г/Ц Блинчики с мясом вес, Россия',
        productBrand: 'РОГАЧЕВ',
        productCountry: 'Россия',
        productWeight: '200г',
        productCategoryId: 4,
        productArticl: '371431',
    },
    {
        id: 2,
        imgProduct: imgProduct2,
        productSales:'-20%',
        productPriceCart:'54',
        productNoCart:'60',
        productName: 'Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное 1л',
        productBrand: 'Простоквашино',
        productCountry: 'Россия',
        productWeight: '987г',
        productCategoryId: 1,
        productArticl: '371432',
    },
    {
        id: 3,
        imgProduct: imgProduct3,
        productSales:'-10%',
        productPriceCart:'77',
        productNoCart:'82',
        productName: 'Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскано',
        productBrand: 'МЯСНАЯ ИСТОРИЯ',
        productCountry: 'Россия',
        productWeight: '450г',
        productCategoryId: 11,
        productArticl: '371433',
    },
    {
        id: 4,
        imgProduct: imgProduct4,
        productSales:'-10%',
        productPriceCart:'224',
        productNoCart:'254',
        productName: 'Колбаса Папа может Чесночная полукопченая 350г',
        productBrand: 'Папа может',
        productCountry: 'Россия',
        productWeight: '350г',
        productCategoryId: 11,
        productArticl: '371434',
    },
    {
        id: 5,
        imgProduct: imgProduct5,
        productSales:'-5%',
        productPriceCart:'349',
        productNoCart:'399',
        productName: 'Колбаса Ближние Горки Новомосковская варено-копченая 350г',
        productBrand: 'Ближние горки',
        productCountry: 'Россия',
        productWeight: '350г',
        productCategoryId: 11,
        productArticl: '371435',
    },
    {
        id: 6,
        imgProduct: imgProduct6,
        productSales:'-15%',
        productPriceCart:'77',
        productNoCart:'90',
        productName: 'Колбаса «ДЕСНА-ПОЛЕСЬЕ 0.4 кг»',
        productBrand: 'БРЯНСКСЕЛЬМАШ',
        productCountry: 'Россия',
        productWeight: '400г',
        productCategoryId: 11,
        productArticl: '371436',
    },
    {
        id: 7,
        imgProduct: imgProduct7,
        productSales:'-15%',
        productPriceCart:'140',
        productNoCart: '156',
        productName: 'Сыр Dorbly 300гр.',
        productBrand: 'Dorbly',
        productCountry: 'Россия',
        productWeight: '300г',
        productCategoryId: 1,
        productArticl: '371437',
    },
    {
        id: 8,
        imgProduct: imgProduct8,
        productSales:'-25%',
        productPriceCart:'78',
        productNoCart:'90',
        productName: 'Молоко сгущенное РОГАЧЕВ Егорка, цельное с сахаром',
        productBrand: 'РОГАЧЕВ',
        productCountry: 'Россия',
        productWeight: '400г',
        productCategoryId: 1,
        productArticl: '371438',
    },
    {
        id: 9,
        imgProduct: imgProduct9,
        productSales:'-18%',
        productPriceCart:'192',
        productNoCart:'215',
        productName: 'Масло сливочное 82% Простоквашино',
        productBrand: 'Простоквашино',
        productCountry: 'Россия',
        productWeight: '200г',
        productCategoryId: 1,
        productArticl: '371439',
    },
    {
        id: 10,
        imgProduct: imgProduct10,
        productSales:'-19%',
        productPriceCart:'29',
        productNoCart:'34',
        productName: 'Йогурт Fruttis 70гр. Дыня',
        productBrand: 'Fruttis',
        productCountry: 'Россия',
        productWeight: '70г',
        productCategoryId: 1,
        productArticl: '371440',
    },
    {
        id: 11,
        imgProduct: imgProduct11,
        productSales:'-19%',
        productPriceCart:'29',
        productNoCart:'34',
        productName: 'Йогурт Fruttis 70гр. Ягода',
        productBrand: 'Fruttis',
        productCountry: 'Россия',
        productWeight: '70г',
        productCategoryId: 1,
        productArticl: '371441',
    },
    {
        id: 12,
        imgProduct: imgProduct12,
        productSales:'-19%',
        productPriceCart:'109',
        productNoCart:'120',
        productName: 'Томатная паста Global Village 270г',
        productBrand: 'Global Village',
        productCountry: 'Россия',
        productWeight: '270г',
        productCategoryId: 3,
        productArticl: '371442',
    },  
    {
        id: 13,
        imgProduct: imgProduct13,
        productSales:'-10%',
        productPriceCart:'119',
        productNoCart:'129',
        productName: 'Нектар Global Village ананасовый 950мл',
        productBrand: 'Global Village',
        productCountry: 'Россия',
        productWeight: '950г',
        productCategoryId: 5,
        productArticl: '371443',
    }, 
    {
        id: 14,
        imgProduct: imgProduct14,
        productSales:'-12%',
        productPriceCart:'179',
        productNoCart:'185',
        productName: 'Огурцы Global Village корнишоны маринованные 720мл',
        productBrand: 'Global Village',
        productCountry: 'Россия',
        productWeight: '720г',
        productCategoryId: 3,
        productArticl: '371444',
    },
    {
        id: 15,
        imgProduct: imgProduct15,
        productSales:'-15%',
        productPriceCart:'129',
        productNoCart:'140',
        productName: 'Огурцы соленые Global Village 680г',
        productBrand: 'Global Village',
        productCountry: 'Россия',
        productWeight: '680г',
        productCategoryId: 3,
        productArticl: '371445',
    },
    {
        id: 16,
        imgProduct: imgProduct16,
        productSales:'-11%',
        productPriceCart:'139',
        productNoCart:'146',
        productName: 'Смесь овощная Global Village 8 Овощей 400г',
        productBrand: 'Global Village',
        productCountry: 'Россия',
        productWeight: '400г',
        productCategoryId: 3,
        productArticl: '371446',
    }, 
    {
        id: 17,
        imgProduct: imgProduct17,
        productSales:'-21%',
        productPriceCart:'299',
        productNoCart:'319',
        productName: 'Картофель Global Village Selection фри 700г',
        productBrand: 'Global Village',
        productCountry: 'Россия',
        productWeight: '700г',
        productCategoryId: 3,
        productArticl: '371447',
    }, 
    {
        id: 18,
        imgProduct: imgProduct18,
        productSales:'-12%',
        productPriceCart:'77',
        productNoCart:'85,',
        productName: 'Печенье Шарлиз сдобное клубника 137г',
        productBrand: 'Шарлиз',
        productCountry: 'Россия',
        productWeight: '137г',
        productCategoryId: 6,
        productArticl: '371448',
    },
    {
        id: 19,
        imgProduct: imgProduct19,
        productSales:'-12%',
        productPriceCart:'109',
        productNoCart:'115',
        productName: 'Печенье Шарлиз Американо сдобное 250г',
        productBrand: 'Шарлиз',
        productCountry: 'Россия',
        productWeight: '250г',
        productCategoryId: 6,
        productArticl: '371449',
    },
    {
        id: 20,
        imgProduct: imgProduct20,
        productSales:'-18%',
        productPriceCart:'39',
        productNoCart:'45',
        productName: 'Вода минеральная Societe Minerale газированная 1.5л',
        productBrand: 'Societe Minerale',
        productCountry: 'Россия',
        productWeight: '1600г',
        productCategoryId: 5,
        productArticl: '371450',
    },
    {
        id: 21,
        imgProduct: imgProduct21,
        productSales:'-15%',
        productPriceCart:'59',
        productNoCart:'65',
        productName: 'Вода минеральная Societe Minerale газированная 1.5л',
        productBrand: 'Societe Minerale',
        productCountry: 'Россия',
        productWeight: '1600г',
        productCategoryId: 5,
        productArticl: '371451',
    },
    {
        id: 22,
        imgProduct: imgProduct22,
        productSales:'-10%',
        productPriceCart:'429',
        productNoCart:'450',
        productName: 'Форель Fish House слабосоленая филе-кусок 200г',
        productBrand: 'Fish House',
        productCountry: 'Россия',
        productWeight: '200г',
        productCategoryId: 11,
        productArticl: '371452',
    },
    {
        id: 23,
        imgProduct: imgProduct23,
        productSales:'-15%',
        productPriceCart:'99',
        productNoCart:'105',
        productName: 'Икра имитированная Fish House красная 220г',
        productBrand: 'Fish House',
        productCountry: 'Россия',
        productWeight: '220г',
        productCategoryId: 11,
        productArticl: '371453',
    },
    {
        id: 24,
        imgProduct: imgProduct24,
        productSales:'-15%',
        productPriceCart:'89',
        productNoCart:'96',
        productName: 'Карбонад Мясная Ферма из свинины копчено-вареный 100г',
        productBrand: 'Мясная Ферма',
        productCountry: 'Россия',
        productWeight: '100г',
        productCategoryId: 11,
        productArticl: '371454',
    },
];

export default ArrProducts;