import imgProduct1 from './img/product-1.png';
import imgProduct2 from './img/product-2.png';
import imgProduct3 from './img/product-3.png';
import imgProduct4 from './img/product-4.png';
import imgProduct5 from './img/product-5.png';
import imgProduct6 from './img/product-6.png';
import imgProduct7 from './img/product-7.png';
import imgProduct8 from './img/product-8.png';
import imgProduct9 from './img/product-9.png';
import imgProduct10 from './img/product-10.png';
import imgProduct11 from './img/product-11.png';
import imgProduct12 from './img/product-12.png';
import imgProduct13 from './img/product-13.png';
import imgProduct14 from './img/product-14.png';
import imgProduct15 from './img/product-15.png';
import imgProduct16 from './img/product-16.png';
import imgProduct17 from './img/product-17.png';
import imgProduct18 from './img/product-18.png';
import imgProduct19 from './img/product-19.png';
import imgProduct20 from './img/product-20.png';
import imgProduct21 from './img/product-21.png';
import imgProduct22 from './img/product-22.png';
import imgProduct23 from './img/product-23.png';
import imgProduct24 from './img/product-24.png';
import imgProduct25 from './img/product-25.png';
import imgProduct26 from './img/product-26.png';
import imgProduct27 from './img/product-27.png';
import imgProduct28 from './img/product-28.png';
import imgProduct29 from './img/product-29.png';
import imgProduct30 from './img/product-30.png';
import imgProduct31 from './img/product-31.png';
import imgProduct32 from './img/product-32.png';
import imgProduct33 from './img/product-33.png';
import imgProduct34 from './img/product-34.png';
import imgProduct35 from './img/product-35.png';
import imgProduct36 from './img/product-36.png';
import imgProduct37 from './img/product-37.png';
import imgProduct38 from './img/product-38.png';
import imgProduct39 from './img/product-39.png';
import imgProduct40 from './img/product-40.png';
import imgProduct41 from './img/product-41.png';
import imgProduct42 from './img/product-42.png';
import imgProduct43 from './img/product-43.png';
import imgProduct44 from './img/product-44.png';
import imgProduct45 from './img/product-45.png';
import imgProduct46 from './img/product-46.png';
import imgProduct47 from './img/product-47.png';
import imgProduct48 from './img/product-48.png';
import imgProduct49 from './img/product-49.png';
import imgProduct50 from './img/product-50.png';
import imgProduct51 from './img/product-51.png';
import imgProduct52 from './img/product-52.png';
import imgProduct53 from './img/product-53.png';

const ArrProducts = [
    {
        id: 1,
        imgProduct: imgProduct1,
        productSales:'-30%',
        productPriceCart:'44',
        productNoCart:'48',
        productName: 'Г/Ц Блинчики с мясом вес, Россия',
        productBrand: 'РОГАЧЕВ',
        productCountry: 'Россия',
        productWeight: '200г',
        productCategoryId: 4,
        productArticl: '371431',
    },
    {
        id: 2,
        imgProduct: imgProduct2,
        productSales:'-20%',
        productPriceCart:'54',
        productNoCart:'60',
        productName: 'Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное 1л',
        productBrand: 'Простоквашино',
        productCountry: 'Россия',
        productWeight: '987г',
        productCategoryId: 1,
        productArticl: '371432',
    },
    {
        id: 3,
        imgProduct: imgProduct3,
        productSales:'-10%',
        productPriceCart:'77',
        productNoCart:'82',
        productName: 'Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскано',
        productBrand: 'МЯСНАЯ ИСТОРИЯ',
        productCountry: 'Россия',
        productWeight: '450г',
        productCategoryId: 11,
        productArticl: '371433',
    },
    {
        id: 4,
        imgProduct: imgProduct4,
        productSales:'-10%',
        productPriceCart:'224',
        productNoCart:'254',
        productName: 'Колбаса Папа может Чесночная полукопченая 350г',
        productBrand: 'Папа может',
        productCountry: 'Россия',
        productWeight: '350г',
        productCategoryId: 11,
        productArticl: '371434',
    },
    {
        id: 5,
        imgProduct: imgProduct5,
        productSales:'-5%',
        productPriceCart:'349',
        productNoCart:'399',
        productName: 'Колбаса Ближние Горки Новомосковская варено-копченая 350г',
        productBrand: 'Ближние горки',
        productCountry: 'Россия',
        productWeight: '350г',
        productCategoryId: 11,
        productArticl: '371435',
    },
    {
        id: 6,
        imgProduct: imgProduct6,
        productSales:'-15%',
        productPriceCart:'77',
        productNoCart:'90',
        productName: 'Колбаса «ДЕСНА-ПОЛЕСЬЕ 0.4 кг»',
        productBrand: 'БРЯНСКСЕЛЬМАШ',
        productCountry: 'Россия',
        productWeight: '400г',
        productCategoryId: 11,
        productArticl: '371436',
    },
    {
        id: 7,
        imgProduct: imgProduct7,
        productSales:'-15%',
        productPriceCart:'140',
        productNoCart: '156',
        productName: 'Сыр Dorbly 300гр.',
        productBrand: 'Dorbly',
        productCountry: 'Россия',
        productWeight: '300г',
        productCategoryId: 1,
        productArticl: '371437',
    },
    {
        id: 8,
        imgProduct: imgProduct8,
        productSales:'-25%',
        productPriceCart:'78',
        productNoCart:'90',
        productName: 'Молоко сгущенное РОГАЧЕВ Егорка, цельное с сахаром',
        productBrand: 'РОГАЧЕВ',
        productCountry: 'Россия',
        productWeight: '400г',
        productCategoryId: 1,
        productArticl: '371438',
    },
    {
        id: 9,
        imgProduct: imgProduct9,
        productSales:'-18%',
        productPriceCart:'192',
        productNoCart:'215',
        productName: 'Масло сливочное 82% Простоквашино',
        productBrand: 'Простоквашино',
        productCountry: 'Россия',
        productWeight: '200г',
        productCategoryId: 1,
        productArticl: '371439',
    },
    {
        id: 10,
        imgProduct: imgProduct10,
        productSales:'-19%',
        productPriceCart:'29',
        productNoCart:'34',
        productName: 'Йогурт Fruttis 70гр. Дыня',
        productBrand: 'Fruttis',
        productCountry: 'Россия',
        productWeight: '70г',
        productCategoryId: 1,
        productArticl: '371440',
    },
    {
        id: 11,
        imgProduct: imgProduct11,
        productSales:'-19%',
        productPriceCart:'29',
        productNoCart:'34',
        productName: 'Йогурт Fruttis 70гр. Ягода',
        productBrand: 'Fruttis',
        productCountry: 'Россия',
        productWeight: '70г',
        productCategoryId: 1,
        productArticl: '371441',
    },
    {
        id: 12,
        imgProduct: imgProduct12,
        productSales:'-19%',
        productPriceCart:'109',
        productNoCart:'120',
        productName: 'Томатная паста Global Village 270г',
        productBrand: 'Global Village',
        productCountry: 'Россия',
        productWeight: '270г',
        productCategoryId: 3,
        productArticl: '371442',
    },  
    {
        id: 13,
        imgProduct: imgProduct13,
        productSales:'-10%',
        productPriceCart:'119',
        productNoCart:'129',
        productName: 'Нектар Global Village ананасовый 950мл',
        productBrand: 'Global Village',
        productCountry: 'Россия',
        productWeight: '950г',
        productCategoryId: 5,
        productArticl: '371443',
    }, 
    {
        id: 14,
        imgProduct: imgProduct14,
        productSales:'-12%',
        productPriceCart:'179',
        productNoCart:'185',
        productName: 'Огурцы Global Village корнишоны маринованные 720мл',
        productBrand: 'Global Village',
        productCountry: 'Россия',
        productWeight: '720г',
        productCategoryId: 3,
        productArticl: '371444',
    },
    {
        id: 15,
        imgProduct: imgProduct15,
        productSales:'-15%',
        productPriceCart:'129',
        productNoCart:'140',
        productName: 'Огурцы соленые Global Village 680г',
        productBrand: 'Global Village',
        productCountry: 'Россия',
        productWeight: '680г',
        productCategoryId: 3,
        productArticl: '371445',
    },
    {
        id: 16,
        imgProduct: imgProduct16,
        productSales:'-11%',
        productPriceCart:'139',
        productNoCart:'146',
        productName: 'Смесь овощная Global Village 8 Овощей 400г',
        productBrand: 'Global Village',
        productCountry: 'Россия',
        productWeight: '400г',
        productCategoryId: 3,
        productArticl: '371446',
    }, 
    {
        id: 17,
        imgProduct: imgProduct17,
        productSales:'-21%',
        productPriceCart:'299',
        productNoCart:'319',
        productName: 'Картофель Global Village Selection фри 700г',
        productBrand: 'Global Village',
        productCountry: 'Россия',
        productWeight: '700г',
        productCategoryId: 3,
        productArticl: '371447',
    }, 
    {
        id: 18,
        imgProduct: imgProduct18,
        productSales:'-12%',
        productPriceCart:'77',
        productNoCart:'85,',
        productName: 'Печенье Шарлиз сдобное клубника 137г',
        productBrand: 'Шарлиз',
        productCountry: 'Россия',
        productWeight: '137г',
        productCategoryId: 6,
        productArticl: '371448',
    },
    {
        id: 19,
        imgProduct: imgProduct19,
        productSales:'-12%',
        productPriceCart:'109',
        productNoCart:'115',
        productName: 'Печенье Шарлиз Американо сдобное 250г',
        productBrand: 'Шарлиз',
        productCountry: 'Россия',
        productWeight: '250г',
        productCategoryId: 6,
        productArticl: '371449',
    },
    {
        id: 20,
        imgProduct: imgProduct20,
        productSales:'-18%',
        productPriceCart:'39',
        productNoCart:'45',
        productName: 'Вода минеральная Societe Minerale газированная 1.5л',
        productBrand: 'Societe Minerale',
        productCountry: 'Россия',
        productWeight: '1600г',
        productCategoryId: 5,
        productArticl: '371450',
    },
    {
        id: 21,
        imgProduct: imgProduct21,
        productSales:'-15%',
        productPriceCart:'59',
        productNoCart:'65',
        productName: 'Вода минеральная Societe Minerale газированная 1.5л',
        productBrand: 'Societe Minerale',
        productCountry: 'Россия',
        productWeight: '1600г',
        productCategoryId: 5,
        productArticl: '371451',
    },
    {
        id: 22,
        imgProduct: imgProduct22,
        productSales:'-10%',
        productPriceCart:'429',
        productNoCart:'450',
        productName: 'Форель Fish House слабосоленая филе-кусок 200г',
        productBrand: 'Fish House',
        productCountry: 'Россия',
        productWeight: '200г',
        productCategoryId: 11,
        productArticl: '371452',
    },
    {
        id: 23,
        imgProduct: imgProduct23,
        productSales:'-15%',
        productPriceCart:'99',
        productNoCart:'105',
        productName: 'Икра имитированная Fish House красная 220г',
        productBrand: 'Fish House',
        productCountry: 'Россия',
        productWeight: '220г',
        productCategoryId: 11,
        productArticl: '371453',
    },
    {
        id: 24,
        imgProduct: imgProduct24,
        productSales:'-15%',
        productPriceCart:'89',
        productNoCart:'96',
        productName: 'Карбонад Мясная Ферма из свинины копчено-вареный 100г',
        productBrand: 'Мясная Ферма',
        productCountry: 'Россия',
        productWeight: '100г',
        productCategoryId: 11,
        productArticl: '371454',
    },
    {
        id: 25,
        imgProduct: imgProduct25,
        productSales:'-10%',
        productPriceCart:'55',
        productNoCart:'63',
        productName: 'Батон Хлебный Дом Звездный нарезка 350г',
        productBrand: 'Хлебный Дом',
        productCountry: 'Россия',
        productWeight: '350г',
        productCategoryId: 2,
        productArticl: '371455',
    },
    {
        id: 26,
        imgProduct: imgProduct26,
        productSales:'-11%',
        productPriceCart:'18',
        productNoCart:'22',
        productName: 'Хлеб Красная Цена Белый 380г',
        productBrand: 'Красная цена',
        productCountry: 'Россия',
        productWeight: '380г',
        productCategoryId: 2,
        productArticl: '371456',
    },
    {
        id: 27,
        imgProduct: imgProduct27,
        productSales:'-15%',
        productPriceCart:'120',
        productNoCart:'141',
        productName: "Хлеб сандвичный Harry's American Sandwich пшеничный с отрубями нарезка 515 г",
        productBrand: "Harry'S",
        productCountry: 'Россия',
        productWeight: '515г',
        productCategoryId: 2,
        productArticl: '371457',
    },
    {
        id: 28,
        imgProduct: imgProduct28,
        productSales:'-10%',
        productPriceCart:'160',
        productNoCart:'180',
        productName: "Булочка Bagerstat для хот-дога 4х60г",
        productBrand: "Bagerstat",
        productCountry: 'Россия',
        productWeight: '541г',
        productCategoryId: 2,
        productArticl: '371458',
    },
    {
        id: 29,
        imgProduct: imgProduct29,
        productSales:'-15%',
        productPriceCart:'65',
        productNoCart:'72',
        productName: "Булочки Коломенский пшеничные с кунжутом 3х60г",
        productBrand: "Коломенский",
        productCountry: 'Россия',
        productWeight: '180',
        productCategoryId: 2,
        productArticl: '371459',
    },
    {
        id: 30,
        imgProduct: imgProduct30,
        productSales:'-10%',
        productPriceCart:'115',
        productNoCart:'129',
        productName: "Крекер Tuc Мини со вкусом сыра соленый 110г",
        productBrand: "Tuc",
        productCountry: 'Россия',
        productWeight: '110',
        productCategoryId: 2,
        productArticl: '371460',
    },
    {
        id: 31,
        imgProduct: imgProduct31,
        productSales:'-10%',
        productPriceCart:'119',
        productNoCart:'129',
        productName: "Яблоки Голден",
        productBrand: "",
        productCountry: 'Россия',
        productWeight: '1000',
        productCategoryId: 3,
        productArticl: '371461',
    },
    {
        id: 32,
        imgProduct: imgProduct32,
        productSales:'-10%',
        productPriceCart:'300',
        productNoCart:'330',
        productName: "Манго спелое Египет",
        productBrand: "",
        productCountry: 'Египет',
        productWeight: '1000',
        productCategoryId: 3,
        productArticl: '371462',
    },
    {
        id: 33,
        imgProduct: imgProduct33,
        productSales:'-10%',
        productPriceCart:'130',
        productNoCart:'140',
        productName: "Гранат",
        productBrand: "",
        productCountry: 'Египет',
        productWeight: '1000',
        productCategoryId: 3,
        productArticl: '371463',
    },
    {
        id: 34,
        imgProduct: imgProduct34,
        productSales:'-10%',
        productPriceCart:'50',
        productNoCart:'55',
        productName: "Мороженое Лакомство Колибри вафельный рожок 12% СЗМЖ 100г",
        productBrand: "Лакомство Колибри",
        productCount: 'Россия',
        productWeight: '100',
        productCategoryId: 4,
        productArticl: '371464',
    },
    {
        id: 35,
        imgProduct: imgProduct35,
        productSales:'-10%',
        productPriceCart:'189',
        productNoCart:'204',
        productName: "Чебупицца Горячая Штучка Курочка по-итальянски 250г",
        productBrand: "Горячая штучка",
        productCountry: 'Россия',
        productWeight: '250',
        productCategoryId: 4,
        productArticl: '371465',
    },
    {
        id: 36,
        imgProduct: imgProduct36,
        productSales:'-10%',
        productPriceCart:'190',
        productNoCart:'208',
        productName: "Пельмени Горячая штучка Бульмени со сливочным маслом 400г",
        productBrand: "Горячая штучка",
        productCountry: 'Россия',
        productWeight: '400',
        productCategoryId: 4,
        productArticl: '371466',
    },
    {
        id: 37,
        imgProduct: imgProduct37,
        productSales:'-10%',
        productPriceCart:'130',
        productNoCart:'149',
        productName: "Вареники Рестория с картофелем и грибами 450г",
        productBrand: "Рестория",
        productCountry: 'Россия',
        productWeight: '450',
        productCategoryId: 4,
        productArticl: '371467',
    },
    {
        id: 38,
        imgProduct: imgProduct38,
        productSales:'-10%',
        productPriceCart:'130',
        productNoCart:'149',
        productName: "Вареники Рестория с вишней 450г",
        productBrand: "Рестория",
        productCountry: 'Россия',
        productWeight: '450',
        productCategoryId: 4,
        productArticl: '371467',
    },
    {
        id: 39,
        imgProduct: imgProduct39,
        productSales:'-10%',
        productPriceCart:'130',
        productNoCart:'149',
        productName: "Треугольники рыбные Polar в панировке 300г",
        productBrand: "Рестория",
        productCountry: 'Россия',
        productWeight: '450',
        productCategoryId: 4,
        productArticl: '371467',
    },
    {
        id: 40,
        imgProduct: imgProduct40,
        productSales:'-10%',
        productPriceCart:'55',
        productNoCart:'59',
        productName: "Вода Святой источник природная газированная 1.5л",
        productBrand: "Святой Источник",
        productCountry: 'Россия',
        productWeight: '1500',
        productCategoryId: 5,
        productArticl: '371468',
    },
    {
        id: 41,
        imgProduct: imgProduct41,
        productSales:'-10%',
        productPriceCart:'19',
        productNoCart:'23',
        productName: "Сок Сады Придонья зеленое яблоко 125мл",
        productBrand: "Сады Придонья",
        productCountry: 'Россия',
        productWeight: '125',
        productCategoryId: 5,
        productArticl: '371469',
    },
    {
        id: 42,
        imgProduct: imgProduct42,
        productSales:'-10%',
        productPriceCart:'120',
        productNoCart:'139',
        productName: "Напиток Добрый Кола газированный 1.5л",
        productBrand: "Добрый",
        productCountry: 'Россия',
        productWeight: '1500',
        productCategoryId: 5,
        productArticl: '371470',
    },
    {
        id: 43,
        imgProduct: imgProduct43,
        productSales:'-10%',
        productPriceCart:'115',
        productNoCart:'128',
        productName: "Пирожное бисквитное Медвежонок Барни с бананово-йогуртовой начинкой 150г",
        productBrand: "Барни",
        productCountry: 'Россия',
        productWeight: '150',
        productCategoryId: 6,
        productArticl: '371471',
    },
    {
        id: 44,
        imgProduct: imgProduct44,
        productSales:'-10%',
        productPriceCart:'230',
        productNoCart:'246',
        productName: "Эклеры Фили-Бейкер заварные 250г",
        productBrand: "Фили-Бейкер",
        productCountry: 'Россия',
        productWeight: '250',
        productCategoryId: 6,
        productArticl: '371472',
    },
    {
        id: 45,
        imgProduct: imgProduct45,
        productSales:'-10%',
        productPriceCart:'220',
        productNoCart:'236',
        productName: "Пирожные Baker House мини-тарты карамельно-арахисовые 240г",
        productBrand: "Baker House",
        productCountry: 'Россия',
        productWeight: '240',
        productCategoryId: 6,
        productArticl: '371473',
    },
    {
        id: 46,
        imgProduct: imgProduct46,
        productSales:'-10%',
        productPriceCart:'240',
        productNoCart:'257',
        productName: "Пирожные Фили-Бейкер Кольца заварные 300г",
        productBrand: "Фили-Бейкер",
        productCountry: 'Россия',
        productWeight: '300',
        productCategoryId: 6,
        productArticl: '371474',
    },
    {
        id: 47,
        imgProduct: imgProduct47,
        productSales:'-10%',
        productPriceCart:'160',
        productNoCart:'178',
        productName: "Пирожное АМА бисквитное с кремом 160г",
        productBrand: "Ама",
        productCountry: 'Россия',
        productWeight: '160',
        productCategoryId: 6,
        productArticl: '371475',
    },
    {
        id: 48,
        imgProduct: imgProduct48,
        productSales:'-15%',
        productPriceCart:'270',
        productNoCart:'289',
        productName: "Кофе Жокей По-восточному натуральный жареный молотый 250г",
        productBrand: "Жокей",
        productCountry: 'Россия',
        productWeight: '250',
        productCategoryId: 7,
        productArticl: '371476',
    },
    {
        id: 49,
        imgProduct: imgProduct49,
        productSales:'-10%',
        productPriceCart:'344',
        productNoCart:'369',
        productName: "Кофе молотый Monarch Original натуральный жареный 230г",
        productBrand: "Monarch",
        productCountry: 'Россия',
        productWeight: '230',
        productCategoryId: 7,
        productArticl: '371477',
    },
    {
        id: 50,
        imgProduct: imgProduct50,
        productSales:'-10%',
        productPriceCart:'1000',
        productNoCart:'1102',
        productName: "Кофе в зернах Venetto Crema натуральный жареный 1кг",
        productBrand: "Venetto",
        productCountry: 'Италия',
        productWeight: '1000',
        productCategoryId: 7,
        productArticl: '371478',
    },
    {
        id: 51,
        imgProduct: imgProduct51,
        productSales:'-10%',
        productPriceCart:'70',
        productNoCart:'78',
        productName: "Чай черный Азерчай Букет 25х2г",
        productBrand: "Азерчай",
        productCountry: 'Россия',
        productWeight: '50',
        productCategoryId: 7,
        productArticl: '371479',
    },
    {
        id: 52,
        imgProduct: imgProduct52,
        productSales:'-10%',
        productPriceCart:'95',
        productNoCart:'104',
        productName: "Чай черный Greenfield Earl Grey Fantasy с бергамотом 25х2г",
        productBrand: "Greenfield",
        productCountry: 'Россия',
        productWeight: '50',
        productCategoryId: 7,
        productArticl: '371480',
    },
    {
        id: 53,
        imgProduct: imgProduct53,
        productSales:'-10%',
        productPriceCart:'80',
        productNoCart:'89',
        productName: "Чай зеленый Assand Milk Oolong китайский молочный улун 25x2г",
        productBrand: "Assand",
        productCountry: 'Россия',
        productWeight: '50',
        productCategoryId: 7,
        productArticl: '371481',
    },

];

export default ArrProducts;